# Generated by Django 3.0.4 on 2020-03-24 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carmanager', '0002_auto_20200324_2018'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarsList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('engine', models.CharField(max_length=20)),
                ('fuel_count', models.DecimalField(decimal_places=1, max_digits=2)),
                ('color', models.CharField(max_length=20)),
                ('doors', models.IntegerField()),
                ('seatss', models.IntegerField()),
                ('minimum_age', models.IntegerField()),
                ('price', models.IntegerField()),
                ('rating', models.IntegerField()),
                ('carmanager', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='carmanager.CarManager')),
            ],
        ),
    ]
