# Generated by Django 3.0.4 on 2020-03-26 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0012_auto_20200326_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carslist',
            name='fuel_count',
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
    ]
