# Generated by Django 3.0.4 on 2020-03-24 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carmanager', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carmanager',
            old_name='age_date',
            new_name='hire_date',
        ),
    ]
